// Code generated by github.com/jim-minter/go-cosmosdb, DO NOT EDIT.

package cosmosdb

import (
	"context"
	"net/http"
	"strings"

	pkg "github.com/jim-minter/go-cosmosdb/example/types"
)

type personClient struct {
	*databaseClient
	path string
}

// PersonClient is a person client
type PersonClient interface {
	Create(context.Context, string, *pkg.Person, *Options) (*pkg.Person, error)
	List() PersonIterator
	ListAll(context.Context) (*pkg.People, error)
	Get(context.Context, string, string) (*pkg.Person, error)
	Replace(context.Context, string, *pkg.Person, *Options) (*pkg.Person, error)
	Delete(context.Context, string, *pkg.Person, *Options) error
	Query(string, *Query) PersonIterator
	QueryAll(context.Context, string, *Query) (*pkg.People, error)
}

type personListIterator struct {
	*personClient
	continuation string
	done         bool
}

type personQueryIterator struct {
	*personClient
	partitionkey string
	query        *Query
	continuation string
	done         bool
}

// PersonIterator is a person iterator
type PersonIterator interface {
	Next(context.Context) (*pkg.People, error)
}

// NewPersonClient returns a new person client
func NewPersonClient(collc CollectionClient, collid string) PersonClient {
	return &personClient{
		databaseClient: collc.(*collectionClient).databaseClient,
		path:           collc.(*collectionClient).path + "/colls/" + collid,
	}
}

func (c *personClient) all(ctx context.Context, i PersonIterator) (*pkg.People, error) {
	allpeople := &pkg.People{}

	for {
		people, err := i.Next(ctx)
		if err != nil {
			return nil, err
		}
		if people == nil {
			break
		}

		allpeople.Count += people.Count
		allpeople.ResourceID = people.ResourceID
		allpeople.People = append(allpeople.People, people.People...)
	}

	return allpeople, nil
}

func (c *personClient) Create(ctx context.Context, partitionkey string, newperson *pkg.Person, options *Options) (person *pkg.Person, err error) {
	headers := http.Header{}
	headers.Set("X-Ms-Documentdb-Partitionkey", `["`+partitionkey+`"]`)

	if options == nil {
		options = &Options{}
	}
	options.NoETag = true

	err = c.setOptions(options, newperson, headers)
	if err != nil {
		return
	}

	err = c.do(ctx, http.MethodPost, c.path+"/docs", "docs", c.path, http.StatusCreated, &newperson, &person, headers)
	return
}

func (c *personClient) List() PersonIterator {
	return &personListIterator{personClient: c}
}

func (c *personClient) ListAll(ctx context.Context) (*pkg.People, error) {
	return c.all(ctx, c.List())
}

func (c *personClient) Get(ctx context.Context, partitionkey, personid string) (person *pkg.Person, err error) {
	headers := http.Header{}
	headers.Set("X-Ms-Documentdb-Partitionkey", `["`+partitionkey+`"]`)
	err = c.do(ctx, http.MethodGet, c.path+"/docs/"+personid, "docs", c.path+"/docs/"+personid, http.StatusOK, nil, &person, headers)
	return
}

func (c *personClient) Replace(ctx context.Context, partitionkey string, newperson *pkg.Person, options *Options) (person *pkg.Person, err error) {
	headers := http.Header{}
	headers.Set("X-Ms-Documentdb-Partitionkey", `["`+partitionkey+`"]`)

	err = c.setOptions(options, newperson, headers)
	if err != nil {
		return
	}

	err = c.do(ctx, http.MethodPut, c.path+"/docs/"+newperson.ID, "docs", c.path+"/docs/"+newperson.ID, http.StatusOK, &newperson, &person, headers)
	return
}

func (c *personClient) Delete(ctx context.Context, partitionkey string, person *pkg.Person, options *Options) (err error) {
	headers := http.Header{}
	headers.Set("X-Ms-Documentdb-Partitionkey", `["`+partitionkey+`"]`)

	err = c.setOptions(options, person, headers)
	if err != nil {
		return
	}

	err = c.do(ctx, http.MethodDelete, c.path+"/docs/"+person.ID, "docs", c.path+"/docs/"+person.ID, http.StatusNoContent, nil, nil, headers)
	return
}

func (c *personClient) Query(partitionkey string, query *Query) PersonIterator {
	return &personQueryIterator{personClient: c, partitionkey: partitionkey, query: query}
}

func (c *personClient) QueryAll(ctx context.Context, partitionkey string, query *Query) (*pkg.People, error) {
	return c.all(ctx, c.Query(partitionkey, query))
}

func (c *personClient) setOptions(options *Options, person *pkg.Person, headers http.Header) error {
	if options == nil {
		return nil
	}

	if !options.NoETag {
		if person.ETag == "" {
			return ErrETagRequired
		}
		headers.Set("If-Match", person.ETag)
	}
	if len(options.PreTriggers) > 0 {
		headers.Set("X-Ms-Documentdb-Pre-Trigger-Include", strings.Join(options.PreTriggers, ","))
	}
	if len(options.PostTriggers) > 0 {
		headers.Set("X-Ms-Documentdb-Post-Trigger-Include", strings.Join(options.PostTriggers, ","))
	}

	return nil
}

func (i *personListIterator) Next(ctx context.Context) (people *pkg.People, err error) {
	if i.done {
		return
	}

	headers := http.Header{}
	headers.Set("X-Ms-Max-Item-Count", "-1")
	if i.continuation != "" {
		headers.Set("X-Ms-Continuation", i.continuation)
	}

	err = i.do(ctx, http.MethodGet, i.path+"/docs", "docs", i.path, http.StatusOK, nil, &people, headers)
	if err != nil {
		return
	}

	i.continuation = headers.Get("X-Ms-Continuation")
	i.done = i.continuation == ""

	return
}

func (i *personQueryIterator) Next(ctx context.Context) (people *pkg.People, err error) {
	if i.done {
		return
	}

	headers := http.Header{}
	headers.Set("X-Ms-Max-Item-Count", "-1")
	headers.Set("X-Ms-Documentdb-Isquery", "True")
	headers.Set("Content-Type", "application/query+json")
	if i.partitionkey != "" {
		headers.Set("X-Ms-Documentdb-Partitionkey", `["`+i.partitionkey+`"]`)
	} else {
		headers.Set("X-Ms-Documentdb-Query-Enablecrosspartition", "True")
	}
	if i.continuation != "" {
		headers.Set("X-Ms-Continuation", i.continuation)
	}

	err = i.do(ctx, http.MethodPost, i.path+"/docs", "docs", i.path, http.StatusOK, &i.query, &people, headers)
	if err != nil {
		return
	}

	i.continuation = headers.Get("X-Ms-Continuation")
	i.done = i.continuation == ""

	return
}
